//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Client
    {
        public System.Guid id_client { get; set; }
        public string n_f { get; set; }
        public string n_i { get; set; }
        public string n_o { get; set; }
        public string addr { get; set; }
        public string prim { get; set; }
    }
}
