//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Usluga
    {
        public System.Guid id_Usluga { get; set; }
        public string ucode { get; set; }
        public string ucodes { get; set; }
        public string n_usl { get; set; }
    }
}
