//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_204
    {
        public System.Guid id_204 { get; set; }
        public string vers { get; set; }
        public string codotpr { get; set; }
        public string notv { get; set; }
        public string datotv { get; set; }
        public string msgnum { get; set; }
        public string msgdat { get; set; }
        public string result { get; set; }
        public string errmsg { get; set; }
        public Nullable<System.Guid> id_fromerip { get; set; }
        public Nullable<System.DateTime> dent { get; set; }
    }
}
