//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_From210
    {
        public System.Guid id_from { get; set; }
        public string n_msg { get; set; }
        public string dv { get; set; }
        public string n_filename { get; set; }
        public string isHeader { get; set; }
        public string complete { get; set; }
    }
}
