//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Payments
    {
        public System.Guid id_payments { get; set; }
        public string vers { get; set; }
        public string aboncode { get; set; }
        public string msgnum { get; set; }
        public string msgdate { get; set; }
        public string unp { get; set; }
        public string mfo { get; set; }
        public string rsschet { get; set; }
        public string nusl { get; set; }
        public string valcode { get; set; }
        public string lsnum { get; set; }
        public string fio { get; set; }
        public string addr { get; set; }
        public Nullable<decimal> paysum { get; set; }
        public string paydescr { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> dent { get; set; }
        public Nullable<System.DateTime> dlast { get; set; }
        public Nullable<System.Guid> id_toerip { get; set; }
        public Nullable<decimal> zachsum { get; set; }
        public string auths { get; set; }
        public string cartnum { get; set; }
        public string devtype { get; set; }
        public string numoper { get; set; }
    }
}
